export const ADD_TO_CART = "ADD_TO_CART";
export const SHOW_PRODUCTS_IN_CART = "SHOW_PRODUCTS_IN_CART";
export const HIDE_PRODUCTS_IN_CART = "HIDE_PRODUCTS_IN_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
